task :default => "server:start"

namespace :server do
  desc "Initialize the server"
  task :init do
    puts "Initializing the server..."
    # install gem dependencies
    sh "bundle install"
    # generate a random machine id
    sh "rm -f mid; for i in $(seq 1 3); do shuf -i 1-9 -n 1 | xargs echo -n >> mid; done; echo '' >> mid"
  end
  
  desc "Start the server"
  task :start do
    puts "Starting the server..."
    sh "rackup -D"
  end
  
  desc "Stop the server"
  task :stop do
    puts "Stopping the server..."
    run_quietly("kill -9 $(ps aux | grep '[r]ackup' | awk '{print $2}')")
  end
  
  desc "Restart the server"
  task :restart => [:stop, :start] do
  end
  
  def run_quietly(cmd)
    begin
      sh(cmd)
    rescue RuntimeError => e
      puts e.message
    end
  end
end